on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - uses: nrwl/nx-set-shas@v3

      - name: Verify Code
        run: pnpm verify:affected

